/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acromage.gdx;

import acromage.gdx.game.Settings;
import com.badlogic.gdx.ApplicationListener;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.badlogic.gdx.backends.lwjgl.LwjglFrame;
import java.awt.FlowLayout;
import javax.swing.BoxLayout;
import javax.swing.JRootPane;

/**
 *
 * @author admin
 */
public class MainFrame extends LwjglFrame {

    /**
     * Creates new form MainFrame
     * @param listener
     * @param settings
     */
    public MainFrame(ApplicationListener listener, Settings settings) {
        super(listener, "", settings.windowWidth, settings.windowHeight, false);
        initComponents();
        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.PAGE_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuBar = new javax.swing.JMenuBar();
        gameMenu = new javax.swing.JMenu();
        startItem = new javax.swing.JMenuItem();
        separator1 = new javax.swing.JPopupMenu.Separator();
        optionItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Arcomage");
        setResizable(false);

        gameMenu.setText("Игра");

        startItem.setText("Новая");
        gameMenu.add(startItem);
        gameMenu.add(separator1);

        optionItem.setText("Настройки");
        optionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionItemActionPerformed(evt);
            }
        });
        gameMenu.add(optionItem);

        exitItem.setText("Выход");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        gameMenu.add(exitItem);

        mainMenuBar.add(gameMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        dispose();
    }//GEN-LAST:event_exitItemActionPerformed

    private void optionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionItemActionPerformed
        OptionDialog od = new OptionDialog(null, true);
        od.setLocationRelativeTo(null);
        od.setVisible(true);
    }//GEN-LAST:event_optionItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem optionItem;
    private javax.swing.JPopupMenu.Separator separator1;
    private javax.swing.JMenuItem startItem;
    // End of variables declaration//GEN-END:variables
}
